### ISSUE TITLE
`ShapefileException` when running 'Delfland_waterways.ipynb'

### ISSUE THREAD

**Issue by OnnoEbbens** [MAMBA-python/course-material#26]
When I run the notebook 'Delfland_waterways.ipynb' I get this error: ShapefileException: Unable to open shapefiles\boezemwatergangen.dbf or shapefiles\boezemwatergangen.shp.

For now I disabled the test for this notebook

**Comment by pizeboud** [comment]
Fixed - instead reading with geopandas
