### ISSUE TITLE
Error in on_topic/19_pastas/01_basic_pastas_model with function ps.StressModel

### ISSUE THREAD

**Issue by pizeboud** [MAMBA-python/course-material#29]
Gives the error "TypeError: RfuncBase._update_rfunc_settings() missing 1 required positional argument: 'self'"

**Comment by OnnoEbbens** [comment]
Errors in notebook 1-3 are fixed. The last notebook is a bit harder to fix.

**Comment by OnnoEbbens** [comment]
Last notebook is fixed in dev
